#%% 
# -*- coding: utf-8 -*-
"""VQGAN_Prompts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ml8hy_jXDeUR8zjNhEokbZg79QbaD-cz

# VQGAN_Prompts
Generates a random prompt for a VQGAN+CLIP

Creates a text prompt for VQGANs based on a random selection of "things", "places", "colors", "styles", and "artists.

Simply run the code and feed that into your VQGAN.

## Credit to [dughogan](https://github.com/dughogan) orignal project on [Github](https://github.com/dughogan/VQGAN_Prompts)

edited by : [HostsServer](https://github.com/MSFTserver) (only wrapped the function to do multiple prompts at a single time)
"""
#@markdown # 2) Generate random prompt
import random
promptList = []
amount = 10 #@param {type:"number"}

def make_random_prompt(amount):
  for i in range(amount):
    styles = open("styles").read().split()
    index = random.randint(0, len(styles) - 1)
    style = styles[index].capitalize()
    prompt = style + " bouquet"
    r = random.random()

    # things = ["bouquet"]
    shapes = open("shapes").read().splitlines()
    colors = open("colors").read().splitlines()
    artist = open("artists").read().splitlines()

    # if r < 1.0 / 3.0:
    #   series = "shapes"
    #   index_shapes = random.randint(0, len(shapes) - 1)
    #   index_colors = random.randint(0, len(colors) - 1)
    #   subject = " with " + shapes[index_shapes] + " in " + colors[index_colors]
    #   prompt += subject
    # if r < 1.0 / 3.0:
    #   series = "things"
    #   index_things = random.randint(0, len(things) - 1)
    #   index_colors = random.randint(0, len(colors) - 1)
    #   prompt += " of " + things[index_things] + " in the color " + colors[index_colors]

    # index_things = 0

    if r < 1.0 / 4.0:
      series = "shapes and colors"
      index_shapes = random.randint(0, len(shapes) - 1)
      index_colors = random.randint(0, len(colors) - 1)
      subject = " with " + shapes[index_shapes] + " in " + colors[index_colors]
      prompt += subject
    elif r < 4.0 / 6.0:
      series = "shapes"
      index_shapes = random.randint(0, len(shapes) - 1)
      index_colors = random.randint(0, len(colors) - 1)
      index_artist = random.randint(0, len(artist) - 1)
      subject = " with " + shapes[index_shapes] + " in " + colors[index_colors] + " in the style of " + artist[index_artist]
      prompt += subject
    # elif r < 5.0 / 6.0:
    #   series = "things"
    #   index_things = random.randint(0, len(things) - 1)
    #   index_colors = random.randint(0, len(colors) - 1)
    #   index_artist = random.randint(0, len(artist) - 1)
    #   prompt += " of " + things[index_things] + " in the color " + colors[index_colors] + " in the style of " + artist[index_artist]
    else:
      series = "shapes and colors"
      index_shapes = random.randint(0, len(shapes) - 1)
      index_colors = random.randint(0, len(colors) - 1)
      index_artist = random.randint(0, len(artist) - 1)
      subject = " with " + shapes[index_shapes] + " in " + colors[index_colors] + " in the style of " + artist[index_artist]
      prompt += subject

    promptList.append(prompt)

make_random_prompt(amount)

for k in promptList:
  print(k)
# %%
